:pencil: (CONTRIBUTING.md) added ct.yaml config to chart-testing
fixing the following error (e.g: using stable/vpa):
Error: no repository definition for https://kubernetes-sigs.github.io/metrics-server/. Please add the missing repos via 'helm repo add'
due to: https://github.com/helm/helm/issues/8036#issuecomment-627692870
fixed using provisioned ct.yaml in scripts/ folder

Signed-off-by: Llyth <6819575+Llyth@users.noreply.github.com>